/*
2nd tab of GUI
Adding, editing, deleting releases are made here
Also a setting button to set when notifications appear,
export and import CSV
 */
package com.hypesniper.ReleaseOrganizer;

import com.hypesniper.ReleaseOrganizer.auxilliary.ContextMenuMouseListener;
import com.hypesniper.ReleaseOrganizer.model.Release;
import com.hypesniper.ReleaseOrganizer.auxilliary.settingsPopup;
import java.awt.Desktop;
import java.net.URI;
import java.net.URL;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import javax.swing.BorderFactory;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

public class editPanel extends javax.swing.JPanel {

    DataOperationsHandler operationHandler;
    DefaultTableModel model;
    TableRowSorter<DefaultTableModel> sorter;
    Release selectedRelease;
    ArrayList<Release> releases;

    /**
     * Creates new form editPanel
     */
    public editPanel() {
        initComponents();
        model = (DefaultTableModel) tableEditPanel.getModel();
        sorter = new TableRowSorter<>(model);
    }

    public void setOperationHandler(DataOperationsHandler dataOp) {
        this.operationHandler = dataOp;
        releases = operationHandler.getAllReleases();
    }

    // Fills table with release info
    public void populateTable() {
        model.setRowCount(0);
        for (Release r : releases) {
            Object[] rowData
                    = {r.getFormattedDate(), r.getBot(), r.getShopify(),
                        r.getisEarlyLink() ? "Early" : "Collection", r.getLink(),
                        r.getQueue(), r.getNotes()};
            model.addRow(rowData);
        }
    }

    // if a release is double-clicked fills form with release data
    // else clears form
    private void populateForm() {
        if (selectedRelease == null) {
            txtDate.setText("");
            txtNotes.setText("");
            comboIsEarly.setSelectedIndex(0);
            txtSiteLink.setText("");
            txtBotable.setText("");
            comboQueue.setSelectedIndex(0);
            comboShopify.setSelectedIndex(0);
            jPanel2.setBorder(BorderFactory
                    .createTitledBorder("  new release  "));
        } else {
            txtDate.setText(selectedRelease.getFormattedDate());
            txtNotes.setText(selectedRelease.getNotes()); //further
            comboIsEarly.setSelectedItem(selectedRelease.getisEarlyLink() ? "Early" : "Collection");
            txtSiteLink.setText(selectedRelease.getLink());
            txtBotable.setText(selectedRelease.getBot());
            comboQueue.setSelectedItem(selectedRelease.getQueue());
            comboShopify.setSelectedItem(selectedRelease.getShopify());
            jPanel2.setBorder(BorderFactory
                    .createTitledBorder("  edit existing release  "));
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableEditPanel = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        txtDate = new javax.swing.JTextField();
        lblDatetime = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        comboShopify = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        comboQueue = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtSiteLink = new javax.swing.JTextField();
        buttonSave = new javax.swing.JButton();
        buttonCancel = new javax.swing.JButton();
        buttonDelete = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtNotes = new javax.swing.JTextArea();
        comboIsEarly = new javax.swing.JComboBox<>();
        txtBotable = new javax.swing.JTextField();
        buttonDeleteAll = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        buttonSetting = new javax.swing.JButton();
        btnInfo = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        try{
            URL img = new URL("http://hypesniper.com/pabanner.jpg");
            ImageIcon image = new ImageIcon(img);
            bannerLabel = new javax.swing.JLabel("", image, JLabel.CENTER);

            jButton1.setText("jButton1");

            jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

            tableEditPanel.setAutoCreateRowSorter(true);
            tableEditPanel.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
            tableEditPanel.setModel(new javax.swing.table.DefaultTableModel(
                new Object [][] {
                    {null, null, null, null, null, null, null},
                    {null, null, null, null, null, null, null},
                    {null, null, null, null, null, null, null},
                    {null, null, null, null, null, null, null}
                },
                new String [] {
                    "Date", "Bot", "Shopify", "Is Early ", "Link", "Queue", "Notes"
                }
            ) {
                Class[] types = new Class [] {
                    java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
                };
                boolean[] canEdit = new boolean [] {
                    false, false, false, false, false, false, false
                };

                public Class getColumnClass(int columnIndex) {
                    return types [columnIndex];
                }

                public boolean isCellEditable(int rowIndex, int columnIndex) {
                    return canEdit [columnIndex];
                }
            });
            tableEditPanel.setToolTipText("Double-Click to edit or delete!");
            tableEditPanel.setRowHeight(20);
            tableEditPanel.addMouseListener(new java.awt.event.MouseAdapter() {
                public void mouseClicked(java.awt.event.MouseEvent evt) {
                    tableEditPanelMouseClicked(evt);
                }
            });
            jScrollPane1.setViewportView(tableEditPanel);
            if (tableEditPanel.getColumnModel().getColumnCount() > 0) {
                tableEditPanel.getColumnModel().getColumn(0).setPreferredWidth(145);
                tableEditPanel.getColumnModel().getColumn(0).setMaxWidth(160);
                tableEditPanel.getColumnModel().getColumn(1).setMinWidth(60);
                tableEditPanel.getColumnModel().getColumn(1).setPreferredWidth(66);
                tableEditPanel.getColumnModel().getColumn(1).setMaxWidth(90);
                tableEditPanel.getColumnModel().getColumn(2).setMinWidth(50);
                tableEditPanel.getColumnModel().getColumn(2).setPreferredWidth(50);
                tableEditPanel.getColumnModel().getColumn(2).setMaxWidth(60);
                tableEditPanel.getColumnModel().getColumn(3).setPreferredWidth(72);
                tableEditPanel.getColumnModel().getColumn(3).setMaxWidth(88);
                tableEditPanel.getColumnModel().getColumn(5).setMinWidth(45);
                tableEditPanel.getColumnModel().getColumn(5).setPreferredWidth(50);
                tableEditPanel.getColumnModel().getColumn(5).setMaxWidth(60);
            }

            javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
            jPanel1.setLayout(jPanel1Layout);
            jPanel1Layout.setHorizontalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
            );
            jPanel1Layout.setVerticalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 257, Short.MAX_VALUE)
            );

            jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("new release"));
            ContextMenuMouseListener contextMenu = new ContextMenuMouseListener();

            txtDate.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
            txtDate.setToolTipText("e.g: 2019-03-25 14:30");
            txtDate.setNextFocusableComponent(txtNotes);
            txtDate.setPreferredSize(new java.awt.Dimension(240, 22));

            lblDatetime.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
            lblDatetime.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
            lblDatetime.setLabelFor(txtDate);
            lblDatetime.setText("Date (Time) :");
            lblDatetime.setToolTipText("e.g: 2020-03-25 ");
            lblDatetime.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

            jLabel2.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
            jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
            jLabel2.setLabelFor(comboShopify);
            jLabel2.setText("Shopify :");
            jLabel2.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

            comboShopify.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
            comboShopify.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "", "Yes", "No" }));
            comboShopify.setMaximumSize(new java.awt.Dimension(180, 22));
            comboShopify.setMinimumSize(new java.awt.Dimension(130, 22));
            comboShopify.setNextFocusableComponent(txtBotable);
            comboShopify.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    comboShopifyActionPerformed(evt);
                }
            });

            jLabel3.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
            jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
            jLabel3.setLabelFor(txtBotable);
            jLabel3.setText("Botable :");
            jLabel3.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

            jLabel4.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
            jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
            jLabel4.setLabelFor(comboQueue);
            jLabel4.setText("Expect Queue :");
            jLabel4.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

            comboQueue.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
            comboQueue.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "", "Yes", "No" }));
            comboQueue.setMaximumSize(new java.awt.Dimension(180, 22));
            comboQueue.setMinimumSize(new java.awt.Dimension(130, 22));
            comboQueue.setNextFocusableComponent(comboIsEarly);
            comboQueue.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    comboQueueActionPerformed(evt);
                }
            });

            jLabel5.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
            jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
            jLabel5.setLabelFor(comboIsEarly);
            jLabel5.setText("Early Link :");
            jLabel5.setToolTipText("");
            jLabel5.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

            jLabel6.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
            jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
            jLabel6.setLabelFor(txtSiteLink);
            jLabel6.setText("Site/Coll Link :");
            jLabel6.setToolTipText("");
            jLabel6.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

            txtSiteLink.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
            txtSiteLink.setToolTipText("URL here");
            txtSiteLink.setNextFocusableComponent(txtDate);
            txtSiteLink.setPreferredSize(new java.awt.Dimension(240, 22));
            txtSiteLink.addFocusListener(new java.awt.event.FocusAdapter() {
                public void focusLost(java.awt.event.FocusEvent evt) {
                    txtSiteLinkFocusLost(evt);
                }
            });

            buttonSave.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
            buttonSave.setText("Save");
            buttonSave.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    buttonSaveActionPerformed(evt);
                }
            });

            buttonCancel.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
            buttonCancel.setText("Cancel");
            buttonCancel.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    buttonCancelActionPerformed(evt);
                }
            });

            buttonDelete.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
            buttonDelete.setText("Delete");
            buttonDelete.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    buttonDeleteActionPerformed(evt);
                }
            });

            jLabel7.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
            jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
            jLabel7.setLabelFor(txtNotes);
            jLabel7.setText("Notes :");
            jLabel7.setToolTipText("");
            jLabel7.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

            txtNotes.setColumns(20);
            txtNotes.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
            txtNotes.setRows(3);
            txtNotes.setNextFocusableComponent(buttonSave);
            txtNotes.setPreferredSize(new java.awt.Dimension(240, 22));
            jScrollPane2.setViewportView(txtNotes);
            txtNotes.addMouseListener(contextMenu);

            comboIsEarly.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
            comboIsEarly.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "", "Early", "Collection" }));
            comboIsEarly.setMaximumSize(new java.awt.Dimension(180, 22));
            comboIsEarly.setMinimumSize(new java.awt.Dimension(130, 22));
            comboIsEarly.setNextFocusableComponent(txtSiteLink);
            comboIsEarly.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    comboIsEarlyActionPerformed(evt);
                }
            });

            txtBotable.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
            txtBotable.setToolTipText("Enter Bot Name here");
            txtBotable.setMaximumSize(new java.awt.Dimension(180, 22));
            txtBotable.setMinimumSize(new java.awt.Dimension(130, 22));
            txtBotable.setNextFocusableComponent(comboQueue);

            buttonDeleteAll.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
            buttonDeleteAll.setText("Delete All");
            buttonDeleteAll.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    buttonDeleteAllActionPerformed(evt);
                }
            });

            javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
            jPanel2.setLayout(jPanel2Layout);
            jPanel2Layout.setHorizontalGroup(
                jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(10, 10, 10)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(comboQueue, 0, 135, Short.MAX_VALUE)
                            .addGap(10, 10, 10))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(comboIsEarly, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(comboShopify, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(txtBotable, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGap(10, 10, 10)))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txtSiteLink, javax.swing.GroupLayout.DEFAULT_SIZE, 262, Short.MAX_VALUE))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addComponent(lblDatetime, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txtDate, javax.swing.GroupLayout.DEFAULT_SIZE, 260, Short.MAX_VALUE))
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jScrollPane2)))
                            .addGap(2, 2, 2)))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(buttonCancel)
                        .addComponent(buttonSave)
                        .addComponent(buttonDelete)
                        .addComponent(buttonDeleteAll))
                    .addContainerGap())
            );

            jPanel2Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {buttonCancel, buttonDelete, buttonDeleteAll, buttonSave});

            jPanel2Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jLabel2, jLabel3, jLabel4, jLabel5});

            jPanel2Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jLabel6, jLabel7, lblDatetime});

            jPanel2Layout.setVerticalGroup(
                jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel6)
                        .addComponent(buttonSave)
                        .addComponent(comboShopify, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel2)
                        .addComponent(txtSiteLink, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel3)
                                .addComponent(txtBotable, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lblDatetime)
                                .addComponent(txtDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(comboQueue, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel4)
                                        .addComponent(jLabel7))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel5)
                                        .addComponent(comboIsEarly, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(0, 16, Short.MAX_VALUE))
                                .addComponent(jScrollPane2)))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(buttonCancel)
                            .addGap(10, 10, 10)
                            .addComponent(buttonDelete)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(buttonDeleteAll)))
                    .addContainerGap())
            );

            jPanel2Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {buttonCancel, buttonDelete, buttonDeleteAll, buttonSave});

            jPanel2Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jLabel2, jLabel3, jLabel4, jLabel5});

            jPanel2Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jLabel6, jLabel7, lblDatetime});

            jPanel2Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {comboIsEarly, comboQueue, comboShopify, txtBotable});

            jPanel2Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {txtDate, txtSiteLink});

            txtDate.addMouseListener(contextMenu);
            txtSiteLink.addMouseListener(contextMenu);

            jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("   "));

            buttonSetting.setIcon(new javax.swing.ImageIcon(getClass().getResource("/media/settings.png"))); // NOI18N
            buttonSetting.setMaximumSize(new java.awt.Dimension(57, 36));
            buttonSetting.setMinimumSize(new java.awt.Dimension(57, 36));
            buttonSetting.setPreferredSize(new java.awt.Dimension(66, 33));
            buttonSetting.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    buttonSettingActionPerformed(evt);
                }
            });

            btnInfo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/media/info.png"))); // NOI18N
            btnInfo.setPreferredSize(new java.awt.Dimension(66, 33));
            btnInfo.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    btnInfoActionPerformed(evt);
                }
            });

            javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
            jPanel3.setLayout(jPanel3Layout);
            jPanel3Layout.setHorizontalGroup(
                jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(buttonSetting, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addContainerGap())
            );

            jPanel3Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnInfo, buttonSetting});

            jPanel3Layout.setVerticalGroup(
                jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnInfo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(buttonSetting, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap())
            );

            jPanel3Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnInfo, buttonSetting});

            jPanel4.setBorder(javax.swing.BorderFactory.createEtchedBorder());

            if(image.getIconWidth() < 0){
                bannerLabel.setText("Sneaker scraper finds early links, restocks, and sitting stock on 300+ sneaker sites");
            }
        }
        catch(Exception e){
            bannerLabel.setText("Sneaker scraper finds early links, restocks, and sitting stock on 300+ sneaker sites");
        }
        bannerLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        bannerLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bannerLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bannerLabelMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(bannerLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 810, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 66, Short.MAX_VALUE)
            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(bannerLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 66, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4))
        );
    }// </editor-fold>//GEN-END:initComponents

    // deletes http, https and www prefix from beginning of strings
    private String trimURLPrefix(String urlStr) {
        String trimmedUrl;
        trimmedUrl = urlStr.replaceFirst("^(https://|http://)", "");
        trimmedUrl = trimmedUrl.replaceFirst("^(www\\.)", "");
        return trimmedUrl;
    }


    private void comboShopifyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboShopifyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboShopifyActionPerformed

    private void comboQueueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboQueueActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboQueueActionPerformed

    private void tableEditPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableEditPanelMouseClicked
        // If a row is double clicked
        // Form is filled with release data to be deleted
        // Selected release is assigned to selectedRelease variable
        if (evt.getClickCount() == 2) {
            int viewRow = tableEditPanel.getSelectedRow();
            int modelRow = tableEditPanel.convertRowIndexToModel(viewRow);
            selectedRelease = releases.get(modelRow);
            populateForm();
        }
    }//GEN-LAST:event_tableEditPanelMouseClicked

    // clears selectedRelease variable and form
    private void buttonCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCancelActionPerformed
        selectedRelease = null;
        populateForm();
    }//GEN-LAST:event_buttonCancelActionPerformed

    // remove selectedrelease from array and save array to csv
    private void buttonDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonDeleteActionPerformed
        if (selectedRelease == null) {
            JOptionPane.showMessageDialog(jPanel2,
                    "Nothing selected to delete; \n"
                    + "Double click on the table row if you want to \n"
                    + "edit/delete an item.");
        } else {
            int dialogResult = JOptionPane.showConfirmDialog(jPanel2,
                    "This will remove the item. \n"
                    + "This can not be undone.",
                    "Confirm Delete", JOptionPane.OK_CANCEL_OPTION);
            if (dialogResult == JOptionPane.YES_OPTION) {
                releases.remove(selectedRelease);
                selectedRelease = null;
                operationHandler.save();
                populateForm();
                populateTable();
            }
        }
    }//GEN-LAST:event_buttonDeleteActionPerformed

    // save a new release or save edited one
    // checks date format and id site link and is eary link empty
    private void buttonSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSaveActionPerformed
        String message = "";
        SimpleDateFormat dateAndTime = new SimpleDateFormat("yyyy-MM-dd HH:mm");
        SimpleDateFormat onlyDate = new SimpleDateFormat("yyyy-MM-dd");

        String dateString = txtDate.getText().trim();

        Date date = null;
        String shopify = comboShopify.getSelectedItem().toString();
        String queue = comboQueue.getSelectedItem().toString();
        String botable = txtBotable.getText().trim();
        String notes = txtNotes.getText().trim();

        boolean isEarly = false;

        String link = txtSiteLink.getText().trim();

        try { //Check entered date valid
            if ("".equals(dateString)) {
                date = null;
            } else if (dateString.length() == 10) {
                date = onlyDate.parse(dateString);
            } else {
                date = dateAndTime.parse(dateString);
                if (dateString.endsWith("00:00")) {
                    Calendar cal = Calendar.getInstance();
                    cal.setTime(date);
                    cal.add(Calendar.MINUTE, -1);
                    date = cal.getTime();
                }
            }// end try
        } catch (Exception e) {
            message += "Date you entered is not valid\n"
                    + "Please try 'yyyy-MM-dd' format \n\n";
        } // date check end

        if (comboIsEarly.getSelectedItem().toString().equals("Early")) {
            isEarly = true;
        } else if (comboIsEarly.getSelectedItem().toString().equals("Collection")) {
            isEarly = false;
        } else {
            message += "Select Early or Collection Link \n\n";
        } //is early combo check end

        if (link.length() < 6) { //short links
            message += "Link you provided is seems too short! \n\n";
        }// end check links

        if (!"".equals(message)) { // if there is message, there is the problem!
            JOptionPane.showMessageDialog(jPanel2, message);
        } else {// messafe string is blank, no problem!
            if (selectedRelease != null) { //editing an existing one
                selectedRelease.setDate(date);
                selectedRelease.setBot(botable);
                selectedRelease.setQueue(queue);
                selectedRelease.setShopify(shopify);
                selectedRelease.setisEarlyLink(isEarly);
                selectedRelease.setLink(link);
                selectedRelease.setNotes(notes);
            } else { // adding a new release
                Release newRelease = new Release(date, botable, shopify, isEarly, link, queue, notes);
                releases.add(newRelease);
            }
            selectedRelease = null;
            operationHandler.save();
            populateForm();
            populateTable();
        }


    }//GEN-LAST:event_buttonSaveActionPerformed

    private void comboIsEarlyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboIsEarlyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboIsEarlyActionPerformed

    // Clears all releases and saves a blank CSV.
    // past releases remains same
    // A dump file is saved in case
    private void buttonDeleteAllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonDeleteAllActionPerformed
        // TODO add your handling code here:
        int dialogResult = JOptionPane.showConfirmDialog(jPanel2,
                "You are about to remove ALL items. \n"
                + "CSV file be moved under the dump directory.\n",
                "Confirm Delete", JOptionPane.OK_CANCEL_OPTION);
        if (dialogResult == JOptionPane.YES_OPTION) {
            operationHandler.dump();
            selectedRelease = null;
            releases.clear();
            operationHandler.save();
            populateForm();
            populateTable();
        }
    }//GEN-LAST:event_buttonDeleteAllActionPerformed

    // there are known sites which allows queues
    // after after link text area has lost focus
    // checks if entered URL is one of the known sites
    // if so sets queue combo to yes
    private void txtSiteLinkFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtSiteLinkFocusLost
        // TODO add your handling code here:
        String str = trimURLPrefix(txtSiteLink.getText().trim()).split("/")[0];
        String[] knownSites = {"adidas.com", "ruvilla.com",
            "kicksusa.com", "ubiqlife.com", "solebox.com",
            "size.co.uk", "footpatrol.co.uk"};
        for (String domain : knownSites) {
            if (str.toLowerCase().contains(domain)) {
                comboQueue.setSelectedItem("Yes");
                break;
            }
        }

    }//GEN-LAST:event_txtSiteLinkFocusLost

    // Shows settings popup 
    private void buttonSettingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSettingActionPerformed
        // TODO add your handling code here:
        settingsPopup setPanel = new settingsPopup();
        setPanel.setOpHandler(operationHandler);
        setPanel.setSpinner();
        setPanel.setParent(this);
        JOptionPane.showMessageDialog(jPanel2, setPanel, "Settings", JOptionPane.PLAIN_MESSAGE);
    }//GEN-LAST:event_buttonSettingActionPerformed

    private void btnInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInfoActionPerformed
        // TODO add your handling code here:
        String msg = "\n"
                + "You can input your release data to the form and click Save to add a new Release\n"
                + "To edit or delete an existing one, find the item on the table and double-click it,\n "
                + "form will be filled with old values.\n\n"
                + "In the settings menu : \n"
                + "• You can adjust how many minutes before release date\n "
                + "  the notification will pop-up \n"
                + "• Export to CSV file\n"
                + "• Import external CSV file.\n\n";

        JOptionPane.showMessageDialog(this, msg, "Edit Tab Info", JOptionPane.INFORMATION_MESSAGE);

    }//GEN-LAST:event_btnInfoActionPerformed

    private void bannerLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bannerLabelMouseClicked
        // TODO add your handling code here:
        if (Desktop.isDesktopSupported()) {
            try {
                Desktop.getDesktop().browse(new URI("http://hypesniper.com/pagealert.htm"));
            } catch (Exception ex) {
                ex.printStackTrace();
            }
        }
    }//GEN-LAST:event_bannerLabelMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bannerLabel;
    private javax.swing.JButton btnInfo;
    private javax.swing.JButton buttonCancel;
    private javax.swing.JButton buttonDelete;
    private javax.swing.JButton buttonDeleteAll;
    private javax.swing.JButton buttonSave;
    private javax.swing.JButton buttonSetting;
    private javax.swing.JComboBox<String> comboIsEarly;
    private javax.swing.JComboBox<String> comboQueue;
    private javax.swing.JComboBox<String> comboShopify;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblDatetime;
    private javax.swing.JTable tableEditPanel;
    private javax.swing.JTextField txtBotable;
    private javax.swing.JTextField txtDate;
    private javax.swing.JTextArea txtNotes;
    private javax.swing.JTextField txtSiteLink;
    // End of variables declaration//GEN-END:variables
}
