/*
When double click an item on view panel table
view panel cretes a new popupPanel object
then passes the double-clicked release to setLabels method
Finaly displays in a JOptionpane.messageDialog
 */
package com.hypesniper.ReleaseOrganizer.auxilliary;

import com.hypesniper.ReleaseOrganizer.model.Release;
import java.awt.Desktop;
import java.awt.Toolkit;
import java.awt.datatransfer.Clipboard;
import java.awt.datatransfer.StringSelection;
import java.net.URI;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.concurrent.TimeUnit;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;

/**
 *
 * @author merg
 */
public class popupPanel extends javax.swing.JPanel {

    /**
     * Creates new form popupPanel
     */
    public popupPanel() {
        initComponents();
    }

    public void setLabels(Release rel) {
        String date= " - ";
        SimpleDateFormat dayOfWeek =new SimpleDateFormat("EEEE, HH:mm");
        if (rel.getDate() != null) { //Detect if date is within a week
            Date now = new Date();
            Date relDate = rel.getDate();
            long diff = relDate.getTime() - now.getTime();
            long days = TimeUnit.DAYS.convert(diff, TimeUnit.MILLISECONDS);
            // if between next week, display day of week instead of year-month format
            if(days < 7 && days > 1) date = "Next "+dayOfWeek.format(relDate).replace(", 00:00", "");
            else date = rel.getFormattedDate();
        }

        dispBotable.setText(rel.getBot().equals("") ? " - " : rel.getBot());
        dispDate.setText(date);//rel.getFormattedDate().equals("") ? " - " : rel.getFormattedDate());
        dispShopify.setText(rel.getShopify().equals("") ? " - " : rel.getShopify());
        dispQueue.setText(rel.getQueue().equals("") ? " - " : rel.getQueue());
        dispNotes.setText(rel.getNotes().equals("") ? " - " : rel.getNotes());

        if (rel.getisEarlyLink()) {
            lblLink.setText("Early Link :");
        }

        dispLink.setText(rel.getLink());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        dispDate = new javax.swing.JLabel();
        lblLink = new javax.swing.JLabel();
        dispBotable = new javax.swing.JLabel();
        dispShopify = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        dispQueue = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        dispLink = new javax.swing.JTextArea();
        btnHelp = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        dispNotes = new javax.swing.JLabel();

        setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setLabelFor(dispBotable);
        jLabel1.setText("Botable :");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setLabelFor(dispShopify);
        jLabel2.setText("Shopify :");
        jLabel2.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setLabelFor(dispDate);
        jLabel3.setText("Date :");
        jLabel3.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        dispDate.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        dispDate.setText("jLabel1");

        lblLink.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblLink.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblLink.setLabelFor(dispLink);
        lblLink.setText("Site Link :");
        lblLink.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        dispBotable.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        dispBotable.setText("jLabel1");

        dispShopify.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        dispShopify.setText("jLabel1");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setLabelFor(dispQueue);
        jLabel4.setText("Queue :");
        jLabel4.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        dispQueue.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        dispQueue.setText("jLabel1");

        jScrollPane2.setBackground(new java.awt.Color(204, 204, 0));
        jScrollPane2.setBorder(null);

        dispLink.setEditable(false);
        dispLink.setBackground(java.awt.SystemColor.menu);
        dispLink.setColumns(20);
        dispLink.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        dispLink.setForeground(new java.awt.Color(0, 11, 102));
        dispLink.setLineWrap(true);
        dispLink.setRows(1);
        dispLink.setToolTipText("Click to open in browser");
        dispLink.setBorder(null);
        dispLink.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        dispLink.setDisabledTextColor(new java.awt.Color(0, 11, 102));
        dispLink.setOpaque(false);
        dispLink.setPreferredSize(new java.awt.Dimension(220, 40));
        dispLink.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dispLinkMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(dispLink);

        btnHelp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/media/help.png"))); // NOI18N
        btnHelp.setMargin(new java.awt.Insets(0, 0, 0, 0));
        btnHelp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHelpActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setLabelFor(dispQueue);
        jLabel5.setText("Notes :");
        jLabel5.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        dispNotes.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        dispNotes.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        dispNotes.setText("jLabel1");
        dispNotes.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblLink)
                            .addComponent(btnHelp)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 214, Short.MAX_VALUE)
                            .addComponent(dispNotes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(dispDate)
                            .addComponent(dispBotable)
                            .addComponent(dispShopify)
                            .addComponent(dispQueue))))
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jLabel1, jLabel2, jLabel3, lblLink});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(dispDate))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(dispBotable))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(dispShopify))
                .addGap(5, 5, 5)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(dispQueue))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblLink)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnHelp))
                    .addComponent(jScrollPane2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(dispNotes, javax.swing.GroupLayout.DEFAULT_SIZE, 54, Short.MAX_VALUE))
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jLabel1, jLabel2, jLabel3, lblLink});

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {dispBotable, dispDate, dispQueue, dispShopify});

    }// </editor-fold>//GEN-END:initComponents

    private void dispLinkMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dispLinkMouseClicked
        // TODO add your handling code here:
        if (SwingUtilities.isLeftMouseButton(evt)) { //left click opens in browser
            if (Desktop.isDesktopSupported()) {
                try {
                    Desktop.getDesktop().browse(new URI( dispLink.getText()));
                } catch (Exception ex) {
                    ex.printStackTrace();
                }
            }
        } else if (SwingUtilities.isRightMouseButton(evt)) { //right click copies to clipboard
            Clipboard clpbrd = Toolkit.getDefaultToolkit().getSystemClipboard();
            StringSelection stringSelection = new StringSelection(dispLink.getText());
            clpbrd.setContents(stringSelection, null);
            JOptionPane.showMessageDialog(dispQueue, "Link copied to Clipboard", "Copy to Clipboard", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_dispLinkMouseClicked

    private void btnHelpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHelpActionPerformed
        // TODO add your handling code here:
        String msg = "You can click the Link below to open in browser\n"
                + "Or right click to Copy the Link to Clipboard.";

        JOptionPane.showMessageDialog(dispBotable, msg, "Open or Copy URL", JOptionPane.INFORMATION_MESSAGE);

    }//GEN-LAST:event_btnHelpActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnHelp;
    private javax.swing.JLabel dispBotable;
    private javax.swing.JLabel dispDate;
    private javax.swing.JTextArea dispLink;
    private javax.swing.JLabel dispNotes;
    private javax.swing.JLabel dispQueue;
    private javax.swing.JLabel dispShopify;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblLink;
    // End of variables declaration//GEN-END:variables
}
